In [1]:
import torch
from torch_geometric.loader import DataLoader

import os
import os.path as osp

import sys
sys.path.append('src/')
from interface_dataset import InterfaceDataset

---

In [2]:
dataset = InterfaceDataset(root=osp.join('data/InterfaceDataset'))

In [31]:
dataset[0]

Data(y=[1], pos=[6075, 3], title='worm_150', box=[3])

In [3]:
train_dataset, test_dataset = torch.utils.data.random_split(dataset, [0.8, 0.2])

In [30]:
train_dataset[0]

Data(y=[1], pos=[2025, 3], title='droplet_180', box=[3])

Data(y=[1], pos=[6075, 3], title='worm_100', box=[3])

In [4]:
train_loader = DataLoader(dataset, batch_size=10, shuffle=True)

In [5]:
batch = next(iter(train_loader))

In [ ]:
for data in train_loader:
    print(data)

In [25]:
print(batch.y)
print(batch.title)

tensor([3, 3, 0, 4, 3, 2, 1, 4, 3, 1])
['roll_170', 'roll_180', 'droplet_140', 'perforation_170', 'roll_140', 'worm_100', 'doughnut_100', 'perforation_170', 'roll_120', 'doughnut_110']


In [ ]:
for data in train_loader:


In [18]:
torch.tensor([1], dtype=torch.long)

tensor([1])

---

In [23]:
def get_files_recursively(directory, extention=None):
    file_list = []
    for root, _, files in os.walk(directory):
        for file in files:
            subdir = os.path.basename(root)
            if extention is None:
                file_list.append(osp.join(subdir, file))
            elif file.endswith(extention):
                file_list.append(osp.join(subdir, file))

    return file_list

In [25]:
processed_dir = osp.join('data/InterfaceDataset/processed')
[
    osp.join(file)
    for subdir in os.listdir(processed_dir) if osp.isdir(osp.join(processed_dir, subdir))
    for file in get_files_recursively(osp.join(processed_dir, subdir), '.pt')
]

['layer/layer_1.90_0.68_103.59_0.05.pt',
 'layer/layer_1.18_0.47_93.07_0.10.pt',
 'layer/layer_2.92_0.62_177.43_0.01.pt',
 'layer/layer_3.01_0.53_110.31_0.01.pt',
 'layer/layer_1.00_0.76_99.26_0.01.pt',
 'layer/layer_4.06_0.06_119.00_0.18.pt',
 'layer/layer_4.06_0.43_110.83_0.19.pt',
 'layer/layer_1.81_0.57_99.71_0.01.pt',
 'layer/layer_1.85_0.83_166.04_0.05.pt',
 'layer/layer_3.71_0.25_139.47_0.10.pt',
 'layer/layer_1.13_0.15_148.95_0.16.pt',
 'layer/layer_4.12_0.62_170.02_0.05.pt',
 'layer/layer_2.16_0.06_120.57_0.10.pt',
 'layer/layer_1.08_0.44_149.31_0.04.pt',
 'layer/layer_2.03_0.94_121.32_0.00.pt',
 'layer/layer_1.04_0.18_148.04_0.01.pt',
 'layer/layer_1.02_0.14_94.29_0.20.pt',
 'layer/layer_3.20_0.10_162.60_0.15.pt',
 'layer/layer_1.17_0.44_162.31_0.01.pt',
 'layer/layer_1.12_0.06_107.89_0.20.pt',
 'layer/layer_2.72_0.97_96.25_0.00.pt',
 'layer/layer_1.97_0.05_179.38_0.01.pt',
 'layer/layer_4.29_0.22_108.92_0.06.pt',
 'layer/layer_1.76_0.07_152.18_0.10.pt',
 'layer/layer_2.98_0.

In [8]:
[subdir for subdir in os.listdir(processed_dir) if osp.isdir(osp.join(processed_dir, subdir))]

['layer', 'worm', 'roll', 'droplet', 'perforation', 'doughnut']

In [21]:
[file for file in get_files_recursively(osp.join(processed_dir, 'droplet'), 'pt')]

droplet_4.07_0.06_98.73_0.05.pt
Here
droplet_2.92_0.06_112.32_0.00.pt
Here
droplet_1.01_0.06_117.67_0.15.pt
Here
droplet_2.30_0.06_122.97_0.09.pt
Here
droplet_1.10_0.25_92.67_0.07.pt
Here
droplet_3.05_0.06_98.76_0.10.pt
Here
droplet_1.79_0.15_92.48_0.10.pt
Here
droplet_1.17_0.25_139.87_0.10.pt
Here
droplet_3.24_0.15_91.96_0.00.pt
Here
droplet_1.94_0.23_91.04_0.04.pt
Here
droplet_1.29_0.06_118.70_0.01.pt
Here
droplet_1.83_0.07_111.83_0.00.pt
Here
droplet_1.04_0.06_126.49_0.16.pt
Here
droplet_1.06_0.07_126.19_0.21.pt
Here
droplet_1.08_0.06_119.65_0.11.pt
Here
droplet_4.02_0.06_119.42_0.01.pt
Here
droplet_1.96_0.12_116.60_0.04.pt
Here
droplet_3.13_0.06_94.07_0.10.pt
Here
droplet_1.17_0.05_159.02_0.14.pt
Here
droplet_1.23_0.45_118.29_0.01.pt
Here
droplet_1.05_0.25_111.24_0.15.pt
Here
droplet_1.55_0.26_97.89_0.09.pt
Here
droplet_1.31_0.06_160.74_0.15.pt
Here
droplet_1.81_0.05_140.31_0.16.pt
Here
droplet_2.00_0.33_93.76_0.05.pt
Here
droplet_1.08_0.44_121.40_0.01.pt
Here
droplet_2.11_0.17_99.

['droplet/droplet_4.07_0.06_98.73_0.05.pt',
 'droplet/droplet_2.92_0.06_112.32_0.00.pt',
 'droplet/droplet_1.01_0.06_117.67_0.15.pt',
 'droplet/droplet_2.30_0.06_122.97_0.09.pt',
 'droplet/droplet_1.10_0.25_92.67_0.07.pt',
 'droplet/droplet_3.05_0.06_98.76_0.10.pt',
 'droplet/droplet_1.79_0.15_92.48_0.10.pt',
 'droplet/droplet_1.17_0.25_139.87_0.10.pt',
 'droplet/droplet_3.24_0.15_91.96_0.00.pt',
 'droplet/droplet_1.94_0.23_91.04_0.04.pt',
 'droplet/droplet_1.29_0.06_118.70_0.01.pt',
 'droplet/droplet_1.83_0.07_111.83_0.00.pt',
 'droplet/droplet_1.04_0.06_126.49_0.16.pt',
 'droplet/droplet_1.06_0.07_126.19_0.21.pt',
 'droplet/droplet_1.08_0.06_119.65_0.11.pt',
 'droplet/droplet_4.02_0.06_119.42_0.01.pt',
 'droplet/droplet_1.96_0.12_116.60_0.04.pt',
 'droplet/droplet_3.13_0.06_94.07_0.10.pt',
 'droplet/droplet_1.17_0.05_159.02_0.14.pt',
 'droplet/droplet_1.23_0.45_118.29_0.01.pt',
 'droplet/droplet_1.05_0.25_111.24_0.15.pt',
 'droplet/droplet_1.55_0.26_97.89_0.09.pt',
 'droplet/droplet_

---

In [1]:
import groio
import torch

from torch_geometric.data import Data
import torch_geometric.transforms as T
from torch_geometric.transforms import FixedPoints, KNNGraph, RadiusGraph
from torchsummary import summary

import sys
sys.path.append('src/')
from transform import DivideByHeight, CenterViaPBC

sys.path.append('model/')
from PointNet import PointNet

In [13]:
_, atoms, box = groio.parse_file('dump_roll.gro')

# Processing raw_data
title = 'dump'
box = torch.tensor(list(map(float, box.strip().split())), dtype=torch.float32)

pos = torch.zeros((len(atoms), 3), dtype=torch.float32)
for i, atom in enumerate(atoms):
    pos[i, :] = torch.tensor(list(map(float, [atom['x'], atom['y'], atom['z']])), dtype=torch.float32)

data = Data(
    title=title,
    pos=pos,
    box=box,
    y=torch.tensor([3], dtype=torch.long)
)

In [14]:
transform = T.Compose([
    CenterViaPBC(),
    DivideByHeight(H=5.8),
    FixedPoints(num=512),
    KNNGraph(k=6),
    # RadiusGraph(r=0.1),
])

In [15]:
data = transform(data)
data = data.to('cuda:0')

In [5]:
model = PointNet(num_classes=5)
model.load_state_dict(torch.load('pointnet_1024.pt', weights_only=True))
model.to('cuda:0')
model.eval()

PointNet(
  (conv1): PointNetLayer()
  (conv2): PointNetLayer()
  (classifier): Linear(in_features=32, out_features=5, bias=True)
)

In [6]:
logit = model(data.pos, data.edge_index, data.batch).detach().cpu()

In [7]:
print(('{:.2f} '*len(logit.ravel())).format(*(logit.softmax(dim=1).ravel() * 100).tolist()))

0.00 0.15 0.00 0.68 99.17 


In [20]:
data.batch.size()

AttributeError: 'NoneType' object has no attribute 'size'

In [23]:
pytorch_total_params = sum(p.numel() for p in model.parameters())

In [24]:
pytorch_total_params

3653

In [ ]:
Batch.from_data_list(dataset[next(iter(train_loader))])

DataBatch(y=[32], pos=[16384, 3], title=[32], box=[96], edge_index=[2, 98304], batch=[16384], ptr=[33])

In [1]:
import torch

In [2]:
grad = torch.tensor([ 1.8814e-04,  2.5941e-05, -1.6740e-04, -7.3390e-05, -6.1055e-05,
         1.2608e-05, -9.5554e-06,  8.0642e-05,  1.4068e-04,  2.4269e-05,
         1.0021e-04, -5.1076e-05,  1.2270e-05,  1.9619e-04,  1.1754e-04,
        -3.6767e-05, -2.0717e-04, -6.7982e-05, -5.4096e-05, -2.3426e-04,
        -1.4839e-04, -1.1318e-04, -1.1843e-05,  8.9043e-05, -4.6844e-05,
        -1.2222e-04,  8.8615e-05, -2.8715e-05,  2.9323e-05, -4.8580e-05,
         1.8584e-04, -7.7771e-05,  8.4274e-06, -6.0606e-05, -9.0010e-05,
        -3.8842e-05,  1.5200e-04,  4.7626e-05, -3.1831e-05,  6.5354e-05,
        -2.7236e-05, -7.6066e-05,  3.1763e-05,  2.3658e-04,  1.2044e-05,
        -8.4477e-05, -1.0430e-04,  9.1108e-05, -9.4834e-05, -6.3349e-05,
        -1.6138e-04,  3.6862e-05, -1.5105e-04,  1.4902e-04, -4.5652e-07,
         7.8003e-05,  5.7813e-06,  3.5058e-05, -7.6752e-05,  2.5887e-05,
        -1.2068e-04,  7.0774e-05,  1.2386e-04,  1.1315e-04,  1.6940e-04,
         4.3923e-06,  8.8490e-06,  9.8663e-05,  9.3761e-06, -7.7759e-07,
         9.7353e-06,  1.0121e-04, -6.2451e-06, -8.5864e-06, -1.9892e-04,
        -7.8068e-05,  9.3116e-05,  1.4061e-04,  5.3011e-05,  1.4808e-04,
        -2.1595e-05,  3.8779e-05,  6.1268e-05, -1.9795e-04,  1.6070e-04,
         2.7007e-05,  8.4967e-05, -8.4814e-05, -8.5275e-05,  3.2817e-07,
        -2.5599e-06,  1.2148e-04,  5.5537e-05, -6.2879e-05,  3.1428e-06,
         4.3745e-06, -1.5727e-04, -1.4244e-04,  1.9731e-05,  7.6734e-06,
        -5.8103e-05, -6.2313e-05, -1.6453e-05, -2.4899e-05,  6.0742e-05,
         1.1011e-04,  6.8213e-05, -9.9058e-05, -9.1176e-05, -1.1907e-04,
         2.5507e-05])

In [10]:
torch.linalg.norm(grad.view((-1, 3)), dim=1).size()

torch.Size([37])

In [11]:
arr = [26, 39, 29, 48, 38, 46, 41, 43, 27, 42, 28, 30, 32, 50, 44, 33, 34, 35, 36, 45]
arr.extend([8, 23, 21, 4, 6, 19, 11, 12, 10, 0, 15, 16, 3, 9, 25, 31, 37, 24, 1, 2, 5, 7, 13, 14, 17
, 18, 20, 22])

In [14]:
print(sorted(arr))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 41, 42, 43, 44, 45, 46, 48, 50]


In [19]:
len([0.03879833221435547, 0.0362553596496582, 0.07297992706298828, 0.04394960403442383, 0.06615018844604492, 0.04701566696166992, 0.06554651260375977, 0.07471132278442383, 0.033164024353027344, 0.04132986068725586, 0.07763957977294922, 0.0790553092956543, 0.09772729873657227, 0.062010765075683594, 0.09838581085205078, 0.043073177337646484, 0.1143503189086914, 0.09601783752441406, 0.063507080078125, 0.07675695419311523, 0.09217548370361328, 0.10968828201293945, 0.09182882308959961, 0.060541629791259766])

24

In [20]:
len([5, 35, 41, 36, 31, 38, 2, 12, 17, 20, 22, 23, 43, 37, 45, 44, 46, 57, 59, 25, 53, 47, 42, 60])

24

In [22]:
len([0.0387873649597168, 0.048949241638183594, 0.07912731170654297, 0.05420541763305664, 0.0818939208984375, 0.09479665756225586, 0.07875823974609375, 0.18056583404541016, 0.05610942840576172, 0.04354667663574219, 0.06480884552001953, 0.43694543838500977, 0.05881977081298828, 0.08050680160522461, 0.09516143798828125, 0.0471343994140625, 0.03766584396362305, 0.06389951705932617, 0.047551631927490234, 0.06423377990722656, 0.08093023300170898, 0.027762413024902344, 0.08394479751586914] )

23

In [23]:
len([64, 63, 59, 56, 35, 62, 53, 67, 61, 48, 74, 42, 43, 72, 73, 57, 77, 47, 49, 51, 52, 60, 87, 76])

24

In [24]:
len([-7.2527, -6.2870, -6.2332, -8.5746, -6.5225, -8.3191, -7.5713, -7.6924, -8.7311, -8.1757, -6.3033, -8.5789, -6.3469, -7.0682, -6.3411, -9.1919, -5.7562, -5.6454, -7.9700, -6.1967, -8.1538, -5.3130, -5.3739, -7.8328])

24

In [29]:
dft_final_energy = torch.tensor([-7.3656, -7.0413, -7.8744, -8.0345, -6.1781, -6.8241, -7.5388, -6.7391, -8.2405, -7.9349, -7.4391, -7.9651, -8.4225, -6.4304, -5.2327, -7.1084, -6.6768, -8.7864, -6.3190, -7.9564, -5.7893, -8.0160, -7.3786, -7.8174])
dft_delta_energy = torch.tensor([ 1.3875, -1.0891,  2.3044, -0.2766, -2.3253, -0.9264,  0.7800,  1.3864, 3.4590, -0.2752, -0.2709, -0.3313, -0.1228,  1.0063, -3.0785,  0.9026, 0.6986,  2.9929, -1.8911,  1.7281, -2.4152,  2.0916,  0.0000,  0.6079])

In [30]:
initial_energy = torch.tensor([-7.312238693237305, -6.948306560516357, -7.821189880371094, -7.954753398895264, -6.11901283264102, -6.732062816619873, -7.476966381072998, -6.680785179138184, -8.181797981262207, -7.869265079498291, -7.37431991882324, -7.913712978363037, -8.333930969238281, -6.37398624420166, -5.173889636993408, -7.024288654327393, 6.592339038848877, -8.72689437866211, -6.285259246826172, -7.869234085083008, -5.745447158813477, -7.92689132694297, -6.3706817626953125, -7.760173797607422])
optimal_energy = torch.tensor([-7.365921974182129, -7.042224407196045, -7.875667572021484, -8.036816596984863, -6.18249082565376, -6.8249311447143555, -7.5408782958984375, -6.739471912384033, -8.241552352905273, -7.935462474822998, -7.43133644104004, -7.970368385314941, -8.423408508300781, -6.431397438049316, -5.232985973358154, -7.10957050323486, -6.676825523376465, -8.789162635803223, -6.324857711791992, -7.956593990325928, -5.790955543518066, -8.016159057617188, -6.456606864929199, -7.817795276641846])
final_energy = torch.tensor([-7.364090442657471, -7.041830062866211, -7.8761725425720215, -8.035367965698242, -6.182695388793945, -6.823683738708496, -7.542817115783691, -6.74015474319458, -8.24050235748291, -7.934346675872803, -7.4390435218811035, -7.9657301902771, -8.421856880187988, -6.431495189666748, -5.233360290527344, -7.109847068786621, -6.677422046661377, -8.788122177124023, -6.318391799926758, -7.958584785461426, -5.790780067443848, -8.016319274902344, -4.1692914962768555, -7.818218231201172])

In [36]:
dft_delta_energy

tensor([ 1.3875, -1.0891,  2.3044, -0.2766, -2.3253, -0.9264,  0.7800,  1.3864,
         3.4590, -0.2752, -0.2709, -0.3313, -0.1228,  1.0063, -3.0785,  0.9026,
         0.6986,  2.9929, -1.8911,  1.7281, -2.4152,  2.0916,  0.0000,  0.6079])

In [34]:
dft_delta_energy + dft_final_energy

tensor([-5.9781, -8.1304, -5.5700, -8.3111, -8.5034, -7.7505, -6.7588, -5.3527,
        -4.7815, -8.2101, -7.7100, -8.2964, -8.5453, -5.4241, -8.3112, -6.2058,
        -5.9782, -5.7935, -8.2101, -6.2283, -8.2045, -5.9244, -7.3786, -7.2095])

In [35]:
initial_energy

tensor([-7.3122, -6.9483, -7.8212, -7.9548, -6.1190, -6.7321, -7.4770, -6.6808,
        -8.1818, -7.8693, -7.3743, -7.9137, -8.3339, -6.3740, -5.1739, -7.0243,
         6.5923, -8.7269, -6.2853, -7.8692, -5.7454, -7.9269, -6.3707, -7.7602])

In [ ]:
DFTOracale_initial_energy = (tensor(-6.0626), tensor(-6.7242), tensor(-6.8328), tensor(-5.4507), tensor([421/1919]
tensor(-7.5723), tensor(-8.6418), tensor(-7.3338), tensor(-9.2313), tensor(-4.5126), tensor(-5.2510), tensor(-7.
0049), tensor(-4.7785), tensor(-8.4075), tensor(-6.7242), tensor(-6.0626), tensor(-6.8328), tensor(-7.4962), te$
sor(-5.5700), tensor(-5.5455), tensor(-7.5771), tensor(-6.8273), tensor(-8.1199), tensor(-8.8575))
DFT Evaluation time: 222.235
initial_energy [-5.866959095001221, -6.164267063140869, -5.160266399383545, -6.789102554321289, -6.899976253509$
215, -5.632861137390137, -8.363194465637207, -6.887008190155029, -7.27317476272583, -5.798116207122803, -6.9932$
2699890137, -7.74070930480957, -8.189624786376953, -7.51085901260376, -7.476489543914795, -8.994598388671875, -$
.280742645263672, -7.236443519592285, -5.913547992706299, -6.805124282836914, -6.0346550941467285, -5.970300197$
01318, -6.14262056350708, -7.9546356201171875, -8.612191200256348, -7.805221080780029, -5.596470832824707]
